spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_user
    password: wallet_pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true